name: pipeline_new
channels:
  - bioconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - aioeasywebdav=2.4.0=pyha770c72_0
  - aiohttp=3.9.5=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - aragorn=1.2.41=h031d066_1
  - archspec=0.2.2=pyhd8ed1ab_0
  - argtable2=2.13=h14c3975_1001
  - async-timeout=4.0.3=py310h06a4308_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - attrs=23.1.0=py310h06a4308_0
  - barrnap=0.9=hdfd78af_4
  - bcrypt=3.2.0=py310h5eee18b_1
  - bedtools=2.31.1=hf5e1c6e_1
  - binutils_impl_linux-64=2.40=hf600244_0
  - binutils_linux-64=2.40.0=hc2dff05_1
  - blas=1.0=openblas
  - blast=2.14.1=pl5321h6f7f691_0
  - blast-legacy=2.2.26=h9ee0642_3
  - boltons=23.0.0=pyhd8ed1ab_0
  - boto3=1.24.0=pyhd8ed1ab_0
  - botocore=1.27.0=pyhd8ed1ab_0
  - bottleneck=1.3.7=py310ha9d4c09_0
  - brotli=1.0.9=he6710b0_2
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bwa=0.7.17=he4a0461_11
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.24.0=hd590300_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=py310h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - circos=0.69.9=hdfd78af_0
  - clustalo=1.2.4=hdbdd923_7
  - clustalw=2.1=h4ac6f70_9
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=23.11.0=py310hff52083_1
  - conda-content-trust=0.2.0=py310h06a4308_1
  - conda-libmamba-solver=23.12.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - configargparse=1.4=pyhd3eb1b0_0
  - cryptography=41.0.7=py310hb8475ec_1
  - curl=8.5.0=hca28451_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - datrie=0.8.2=py310h7f8727e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diamond=2.1.8=h43eeafb_0
  - distro=1.8.0=pyhd8ed1ab_0
  - docutils=0.18.1=py310h06a4308_3
  - dropbox=11.36.1=py310h06a4308_0
  - entrez-direct=16.2=he881be0_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fastqc=0.12.1=hdfd78af_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - filechunkio=1.8=py_2
  - fmt=10.1.1=h00ab1b0_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.4.0=py310h5eee18b_0
  - ftputil=5.1.0=pyhd8ed1ab_0
  - gawk=5.3.0=ha916aea_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_1
  - gdk-pixbuf=2.42.10=h5eee18b_0
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=11.2.0=h7a446d4_16
  - gfortran_linux-64=11.2.0=hc2dff05_1
  - ghostscript=10.03.1=h59595ed_0
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py310h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glimmerhmm=3.0.4=pl5321h87f3376_5
  - gmp=6.3.0=h59595ed_0
  - gobject-introspection=1.78.1=py310hd56c82f_0
  - google-api-core=2.10.1=py310h06a4308_0
  - google-auth=2.29.0=py310h06a4308_0
  - google-cloud-core=2.3.2=py310h06a4308_0
  - google-cloud-storage=2.6.0=py310h06a4308_0
  - google-crc32c=1.5.0=py310h5eee18b_0
  - google-resumable-media=2.4.0=py310h06a4308_0
  - googleapis-common-protos=1.56.4=py310h06a4308_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=7.1.0=h2e5815a_0
  - grpcio=1.46.3=py310hba10ccf_0
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_1
  - h5py=3.8.0=nompi_py310h0311031_100
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdf5=1.12.2=nompi_h4df4325_101
  - hdmedians=0.14.2=py310h261611a_6
  - hmmer=3.3.2=h87f3376_2
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - imagemagick=7.1.1_5=pl5321h211c493_1
  - infernal=1.1.4=pl5321h031d066_4
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jbig=2.1=hdba287a_0
  - jinja2=3.1.4=py310h06a4308_0
  - jmespath=1.0.1=py310h06a4308_0
  - joblib=1.2.0=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hff52083_3
  - jsonschema=4.19.2=py310h06a4308_0
  - jsonschema-specifications=2023.7.1=py310h06a4308_0
  - k8=0.2.5=hdcf5f25_4
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.21.2=h659d440_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.2=h2aa1ff5_1
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcrc32c=1.1.2=h6a678d5_0
  - libcurl=8.5.0=hca28451_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=13.2.0=h807b86a_3
  - libgd=2.3.3=h6a678d5_3
  - libgfortran=3.0.0=1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h807b86a_3
  - libiconv=1.17=hd590300_2
  - libidn11=1.34=h1cef754_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libmamba=1.5.5=had39da4_0
  - libmambapy=1.5.5=py310h39ff949_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - librsvg=2.56.3=he3f83f7_1
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.27=hfc55251_0
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.6=h6a678d5_1009
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.3=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mafft=7.520=h031d066_3
  - make=4.4.1=hb9d3cd8_0
  - mamba=1.5.5=py310h51d5547_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - megahit=1.2.9=h2e03b76_1
  - menuinst=2.0.1=py310hff52083_0
  - minced=0.4.2=hdfd78af_1
  - miniasm=0.3=he4a0461_3
  - minimap2=2.26=he4a0461_2
  - mpfr=4.2.1=h9458935_0
  - multidict=6.0.4=py310h5eee18b_0
  - munkres=1.0.7=py_1
  - muscle=5.1=h4ac6f70_3
  - nbformat=5.9.2=py310h06a4308_0
  - ncbi-vdb=3.0.0=pl5321h87f3376_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.2.1=py310h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numexpr=2.8.7=py310h286c3b5_0
  - openblas=0.3.4=ha44fe06_0
  - openjdk=11.0.1=h516909a_1016
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.3.1=hb9d3cd8_3
  - paml=4.10.7=h031d066_0
  - pandoc=3.5=ha770c72_0
  - pango=1.50.14=ha41ecd1_2
  - parallel=20231122=ha770c72_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.42=hebb0a14_1
  - perl=5.32.1=4_hd590300_perl5
  - perl-algorithm-diff=1.201=pl5321hd8ed1ab_0
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-b-cow=0.007=pl5321h166bdaf_0
  - perl-base=2.23=pl5321hd8ed1ab_0
  - perl-bio-asn1-entrezgene=1.73=pl5321hdfd78af_3
  - perl-bio-coordinate=1.007001=pl5321hdfd78af_3
  - perl-bio-featureio=1.6.905=pl5321hdfd78af_4
  - perl-bio-samtools=1.43=pl5321he4a0461_4
  - perl-bio-searchio-hmmer=1.7.3=pl5321hdfd78af_0
  - perl-bio-tools-phylo-paml=1.7.3=pl5321hdfd78af_3
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl5321hdfd78af_3
  - perl-bio-tools-run-alignment-tcoffee=1.7.4=pl5321hdfd78af_5
  - perl-bioperl=1.7.8=hdfd78af_1
  - perl-bioperl-core=1.7.8=pl5321hdfd78af_1
  - perl-bioperl-run=1.007003=pl5321hdfd78af_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-class-data-inheritable=0.09=pl5321ha770c72_0
  - perl-clone=0.46=pl5321hec16e2b_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321h166bdaf_0
  - perl-compress-raw-zlib=2.202=pl5321h166bdaf_0
  - perl-config-general=2.65=pl5321hdfd78af_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-data-dumper=2.183=pl5321h166bdaf_0
  - perl-db_file=1.858=pl5321h166bdaf_0
  - perl-devel-stacktrace=2.04=pl5321ha770c72_0
  - perl-digest-hmac=1.04=pl5321hdfd78af_0
  - perl-digest-md5=2.58=pl5321h166bdaf_0
  - perl-digest-perl-md5=1.9=pl5321hdfd78af_2
  - perl-encode=3.19=pl5321h166bdaf_0
  - perl-encode-locale=1.05=pl5321hdfd78af_7
  - perl-exception-class=1.45=pl5321hdfd78af_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-listing=6.16=pl5321hdfd78af_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-slurp-tiny=0.004=pl5321hdfd78af_2
  - perl-file-sort=1.01=pl5321hdfd78af_3
  - perl-file-spec=3.48_01=pl5321hdfd78af_2
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-font-ttf=1.06=pl5321hdfd78af_1
  - perl-gd=2.56=0
  - perl-getopt-long=2.54=pl5321hdfd78af_0
  - perl-html-parser=3.81=pl5321h4ac6f70_1
  - perl-html-tagset=3.20=pl5321hdfd78af_4
  - perl-http-cookies=6.10=pl5321hdfd78af_0
  - perl-http-daemon=6.16=pl5321hdfd78af_0
  - perl-http-date=6.06=pl5321hdfd78af_0
  - perl-http-message=6.36=pl5321hdfd78af_0
  - perl-http-negotiate=6.01=pl5321hdfd78af_4
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-compress=2.201=pl5321hdbdd923_2
  - perl-io-html=1.004=pl5321hdfd78af_0
  - perl-io-socket-ssl=2.075=pl5321hd8ed1ab_0
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-io-tty=1.16=pl5321h166bdaf_0
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-ipc-run=20200505.0=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_0
  - perl-json-xs=2.34=pl5321h4ac6f70_6
  - perl-libwww-perl=6.67=pl5321hdfd78af_0
  - perl-libxml-perl=0.08=pl5321hdfd78af_3
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h031d066_2
  - perl-lwp-mediatypes=6.04=pl5321hdfd78af_1
  - perl-math-bezier=0.01=pl5321hdfd78af_2
  - perl-math-round=0.07=pl5321hdfd78af_2
  - perl-math-vecstat=0.08=pl5321hdfd78af_2
  - perl-mime-base64=3.16=pl5321h166bdaf_0
  - perl-module-build=0.4234=pl5321ha770c72_0
  - perl-module-implementation=0.09=pl5321hdfd78af_3
  - perl-module-runtime=0.016=pl5321hdfd78af_2
  - perl-net-http=6.22=pl5321hdfd78af_0
  - perl-net-ssleay=1.92=pl5321hf14f497_1
  - perl-ntlm=1.09=pl5321hdfd78af_5
  - perl-number-format=1.76=pl5321hdfd78af_0
  - perl-params-validate=1.31=pl5321h031d066_2
  - perl-parent=0.241=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h166bdaf_0
  - perl-readonly=2.05=pl5321hdfd78af_1
  - perl-regexp-common=2017060201=pl5321hdfd78af_1
  - perl-scalar-list-utils=1.63=pl5321h166bdaf_0
  - perl-set-intspan=1.19=pl5321hdfd78af_2
  - perl-socket=2.027=pl5321h031d066_4
  - perl-statistics-basic=1.6611=pl5321hdfd78af_3
  - perl-storable=3.15=pl5321h166bdaf_0
  - perl-sub-uplevel=0.2800=pl5321h166bdaf_0
  - perl-svg=2.87=pl5321hdfd78af_0
  - perl-test-deep=1.130=pl5321hd8ed1ab_0
  - perl-test-differences=0.71=pl5321ha770c72_0
  - perl-test-exception=0.43=pl5321hd8ed1ab_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-most=0.38=pl5321hdfd78af_0
  - perl-test-warn=0.37=pl5321hd8ed1ab_0
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-text-diff=1.45=pl5321hd8ed1ab_0
  - perl-text-format=0.62=pl5321hdfd78af_0
  - perl-time-hires=1.9764=pl5321h031d066_4
  - perl-time-local=1.35=pl5321hdfd78af_0
  - perl-timedate=2.33=pl5321hdfd78af_2
  - perl-tree-dag_node=1.32=pl5321hdfd78af_0
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-uri=5.17=pl5321ha770c72_0
  - perl-url-encode=0.03=pl5321h9ee0642_0
  - perl-www-robotrules=6.02=pl5321hdfd78af_4
  - perl-xml-dom=1.46=pl5321hdfd78af_1
  - perl-xml-dom-xpath=0.14=pl5321hdfd78af_2
  - perl-xml-namespacesupport=1.12=pl5321hd8ed1ab_0
  - perl-xml-parser=2.44_01=pl5321hc3e0081_1003
  - perl-xml-regexp=0.04=pl5321hdfd78af_3
  - perl-xml-sax=1.02=pl5321hd8ed1ab_0
  - perl-xml-sax-base=1.09=pl5321hd8ed1ab_0
  - perl-xml-sax-expat=0.51=pl5321hd8ed1ab_0
  - perl-xml-simple=2.25=pl5321hdfd78af_2
  - perl-xml-xpathengine=0.14=pl5321hdfd78af_3
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h6a678d5_0
  - pilon=1.24=hdfd78af_0
  - pixman=0.43.2=h59595ed_0
  - pkg-config=0.29.2=h1bed415_8
  - pluggy=1.3.0=pyhd8ed1ab_0
  - ply=3.11=py310h06a4308_0
  - poa=2.0=h031d066_5
  - prettytable=3.5.0=py310h06a4308_0
  - prodigal=2.6.3=h031d066_6
  - prokka=1.14.6=pl5321hdfd78af_5
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.25.3=py310h12ddb61_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py310h2372a71_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygraphviz=1.9=py310h5eee18b_0
  - pynacl=1.5.0=py310h5eee18b_0
  - pyopenssl=24.0.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pysftp=0.2.9=pyhd3eb1b0_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.0.2=pyhd8ed1ab_0
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310h06a4308_0
  - python-irodsclient=2.0.1=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=4_cp310
  - pyyaml=6.0.1=py310h5eee18b_0
  - qhull=2020.2=h434a139_5
  - quast=5.2.0=py310pl5321h6cc9453_3
  - unzip
  - r-base=4.3.1=h1ae530e_0
  - r-base64enc=0.1_3=r43hb1dbf0f_1007
  - r-bslib=0.8.0=r43hc72bb7e_0
  - r-cachem=1.1.0=r43hb1dbf0f_1
  - r-cli=3.6.3=r43h0d4f4ea_1
  - r-colorspace=2.1_1=r43hdb488b9_0
  - r-cpp11=0.5.0=r43hc72bb7e_0
  - r-crayon=1.5.3=r43hc72bb7e_1
  - r-digest=0.6.37=r43h0d4f4ea_0
  - r-ellipsis=0.3.2=r43hb1dbf0f_3
  - r-evaluate=1.0.1=r43hc72bb7e_0
  - r-fansi=1.0.6=r43hb1dbf0f_1
  - r-farver=2.1.2=r43ha18555a_1
  - r-fastmap=1.2.0=r43ha18555a_1
  - r-fontawesome=0.5.3=r43hc72bb7e_0
  - r-fs=1.6.4=r43ha18555a_1
  - r-ggplot2=3.5.1=r43hc72bb7e_1
  - r-glue=1.7.0=r43hb1dbf0f_1
  - r-gtable=0.3.6=r43hc72bb7e_0
  - r-highr=0.11=r43hc72bb7e_1
  - r-htmltools=0.5.8.1=r43ha18555a_1
  - r-isoband=0.2.7=r43ha18555a_3
  - r-jquerylib=0.1.4=r43hc72bb7e_3
  - r-jsonlite=1.8.8=r43hb1dbf0f_1
  - r-knitr=1.48=r43hc72bb7e_0
  - r-labeling=0.4.3=r43hc72bb7e_1
  - r-lattice=0.22_6=r43hb1dbf0f_1
  - r-lifecycle=1.0.4=r43hc72bb7e_1
  - r-magrittr=2.0.3=r43hb1dbf0f_3
  - r-mass=7.3_60.0.1=r43hb1dbf0f_1
  - r-matrix=1.6_5=r43he966344_1
  - r-memoise=2.0.1=r43hc72bb7e_3
  - r-mgcv=1.9_1=r43h0d28552_1
  - r-mime=0.12=r43hb1dbf0f_3
  - r-munsell=0.5.1=r43hc72bb7e_1
  - r-nlme=3.1_163=r43h640688f_0
  - r-pillar=1.9.0=r43hc72bb7e_2
  - r-pkgconfig=2.0.3=r43hc72bb7e_4
  - r-ps=1.7.7=r43hdb488b9_0
  - r-r6=2.5.1=r43hc72bb7e_3
  - r-rappdirs=0.3.3=r43hb1dbf0f_3
  - r-rcolorbrewer=1.1_3=r43h785f33e_3
  - r-rlang=1.1.4=r43ha18555a_1
  - r-rmarkdown=2.29=r43hc72bb7e_0
  - r-sass=0.4.9=r43ha18555a_1
  - r-scales=1.3.0=r43hc72bb7e_1
  - r-stringi=1.8.4=r43ha8ce623_2
  - r-systemfonts=1.1.0=r43h38d38ca_1
  - r-tibble=3.2.1=r43hdb488b9_3
  - r-tinytex=0.54=r43hc72bb7e_0
  - r-utf8=1.2.4=r43hb1dbf0f_1
  - r-vctrs=0.6.5=r43h0d4f4ea_1
  - r-viridislite=0.4.2=r43hc72bb7e_2
  - r-withr=3.0.2=r43hc72bb7e_0
  - r-yaml=2.3.10=r43hdb488b9_0
  - racon=1.5.0=hdcf5f25_4
  - ratelimiter=1.2.0=pyhd8ed1ab_1003
  - readline=8.2=h8228510_1
  - referencing=0.30.2=py310h06a4308_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rpds-py=0.10.6=py310hb02cf49_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel.yaml=0.18.5=py310h2372a71_0
  - ruamel.yaml.clib=0.2.7=py310h2372a71_2
  - s3transfer=0.6.0=py310h06a4308_0
  - samtools=1.6=hc3601fc_10
  - scikit-bio=0.5.8=py310h0a54255_1
  - setuptools=65.5.0=py310h06a4308_0
  - setuptools-scm=8.0.4=py310h06a4308_0
  - simplejson=3.17.6=py310h7f8727e_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snakemake=5.10.0=0
  - snakemake-minimal=5.10.0=py_0
  - spades=4.0.0=h5fb382e_1
  - sqlite=3.44.2=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - stone=3.3.1=py310h06a4308_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - t-coffee=12.00.7fb08c2=h26a2512_0
  - tbl2asn-forever=25.7.2f=h031d066_4
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h8bc8fbc_6
  - tomli=2.0.1=py310h06a4308_0
  - toposort=1.10=pyhd8ed1ab_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - typing-extensions=4.11.0=py310h06a4308_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.1.0=py310h5eee18b_0
  - unicycler=0.5.0=py310hdf79db3_4
  - urllib3=1.26.18=py310h06a4308_0
  - viennarna=2.6.4=py310pl5321h6cc9453_0
  - wget=1.21.4=h251f7ec_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h59595ed_0
  - yarl=1.9.3=py310h5eee18b_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py310h1275a96_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - asttokens==2.2.1
      - backcall==0.2.0
      - biom-format==2.1.14
      - cachecontrol==0.12.11
      - click==8.1.3
      - comm==0.1.2
      - contourpy==1.0.7
      - cython==0.29.33
      - debugpy==1.6.6
      - entrypoints==0.4
      - executing==1.2.0
      - fonttools==4.38.0
      - ipykernel==6.20.2
      - ipyparallel==8.4.1
      - ipython==8.9.0
      - jedi==0.18.2
      - jupyter-client==8.0.2
      - jupyter-core==5.2.0
      - matplotlib==3.6.3
      - msgpack==1.0.4
      - natsort==8.2.0
      - nest-asyncio==1.5.6
      - numpy==1.24.1
      - packaging==23.0
      - pandas==1.5.3
      - pip==23.3.2
      - platformdirs==2.6.2
      - prompt-toolkit==3.0.36
      - psutil==5.9.4
      - pygments==2.14.0
      - pytz==2022.7.1
      - pyzmq==25.0.0
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - sourcetracker==2.0.1
      - threadpoolctl==3.5.0
      - tornado==6.2
      - traitlets==5.9.0
      - wcwidth==0.2.6
prefix: /home/ddlab3w3/miniconda3/envs/pipeline_new
