#hybrid_config.yaml
#Set parameters or options for the whole run
#these are the default parameters, only change if you know what you're doing
parameters:
  fastqc: ""
  Trimmomatic: " SLIDINGWINDOW:4:15 MINLEN:36 "
  Chopper:
    quality: "10"
    min_length: "500"
  Flye: 
    options: "-t 8"
    sequencing_type: "" #enter your sequencing type for e.g. --nano-raw, --nano-corr, --pacbio-raw, etc. Refer to https://github.com/mikolmogorov/Flye/blob/flye/docs/USAGE.md for more details
  Pilon: 
    options: "-t 8"
    memory: "8G"
    sequencer: "nanopore" #nanopore or pacbio 
  checkm:
    options: ""
  quast: ""
  fastANI: ""
  Barrnap: ""
  RGI: "--local --clean --include_loose"
  Bakta:
    options: "--min-contig-length 200 --compliant --force"
  Phigaro: "--save-fasta -d"
  mobileog:
    options: "-k 15 -e 1e-20 -p 90 -q 90"
  crispr:
    options: "-st dna -sc partial"
  genovi:
    COGs: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    options: "-cs paradise -bc white "
  antismash: 
    options: "--fullhmmer --clusterhmmer --tigrfam --asf --cc-mibig --cb-general --cb-subclusters --cb-knownclusters --pfam2go --rre --smcog-trees --tfbs"


#Directory where the output is expected
outdir: ""

#list all the samples with their information
samples:
  Genome_1:
    R1: ""
    R2: ""
    L1: ""
    genus: ""
    species: ""
    reference_fasta: ""


